debug: false # Enables condition evaluation report logging at startup.

server:
  port: 8080

spring:
  application:
    name: pdfer-client
  profiles:
    active: pdfer-cli, pdfer-actuator

pdfer:
  web:
    endpoint:
      enable: true
      base_uri: pdfer
      download-uri: download
      mail-uri: mail
  mail:
    enable: true # Enables sending mail through HTTP.
    send-from: pdf.client@monke.org
    smtp-server:
      host: ${SMTP_HOST}
      port: 587
      username: ${SMTP_USERNAME}
      password: ${SMTP_PASSWORD}
      java-mail-properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true

management:
  endpoints:
    web:
      exposure:
        include: health, pdfer-web, pdfer-mail, pdfer-registry

---
spring:
  config:
    activate:
      on-profile: pdfer-cli
  shell:
    interactive:
      enabled: true # By default, Spring Shell disables interactive mode.